# Generated by Django 3.2 on 2023-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique',
        ),
    ]
