# Generated by Django 3.2 on 2023-05-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230517_2031'),
        ('reviews', '0005_review_unique'),
    ]

    operations = [
    ]
